---
- name: Test sudo Semaphore
  hosts: ubuntu
  gather_facts: false

  tasks:

    - name: Usuario SSH
      ansible.builtin.command:
        cmd: whoami
      register: user_ssh

    - name: Mostrar usuario SSH
      ansible.builtin.debug:
        msg: "SSH: {{ user_ssh.stdout }}"

    - name: Usuario con sudo
      ansible.builtin.command:
        cmd: whoami
      become: true
      register: user_sudo

    - name: Mostrar usuario sudo
      ansible.builtin.debug:
        msg: "SUDO: {{ user_sudo.stdout }}"
