---
- name: Test sudo Semaphore
  hosts: ubuntu
  gather_facts: false

  tasks:

    - name: Usuario SSH
      ansible.builtin.command:
        cmd: whoami
      register: user_ssh

    - name: Mostrar usuario SSH
      ansible.builtin.debug:
        msg: "SSH: {{ user_ssh.stdout }}"

    - name: Ejecutar sudo explícitamente
      ansible.builtin.command:
        cmd: sudo -n whoami
      register: sudo_result

    - name: Mostrar resultado sudo
      ansible.builtin.debug:
        msg: "SUDO: {{ sudo_result.stdout }}"
