---
- name: Gestionar servicio Middleware Demo
  hosts: ubuntu
  become: true
  gather_facts: false

  tasks:

    - name: Iniciar servicio
      ansible.builtin.systemd:
        name: middleware-demo
        state: started
      when: service_action == "START"

    - name: Detener servicio
      ansible.builtin.systemd:
        name: middleware-demo
        state: stopped
      when: service_action == "STOP"

    - name: Reiniciar servicio
      ansible.builtin.systemd:
        name: middleware-demo
        state: restarted
      when: service_action == "RESTART"

    - name: Obtener estado
      ansible.builtin.systemd:
        name: middleware-demo
      register: service_status

    - name: Mostrar estado
      ansible.builtin.debug:
        msg:
          - "Servicio: middleware-demo"
          - "Estado: {{ service_status.status.ActiveState }}"
          - "Subestado: {{ service_status.status.SubState }}"
