---
- name: Diagnostico Semaphore
  hosts: ubuntu
  become: true
  gather_facts: false

  tasks:

    - name: Identidad
      ansible.builtin.command:
        cmd: whoami
      register: usuario

    - name: Mostrar usuario
      ansible.builtin.debug:
        var: usuario.stdout

    - name: Ejecutar systemctl status
      ansible.builtin.command:
        cmd: systemctl status middleware-demo --no-pager
      register: estado
      changed_when: false

    - name: Mostrar estado
      ansible.builtin.debug:
        var: estado.stdout_lines
